name = "test-cachified-worker"
main = "src/index.ts"
compatibility_date = "2023-11-30"

compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = 'testing'

[[kv_namespaces]]
binding = "KV"
id = "<ignored>"
preview_id = "<ignored>"
