name = "test-cachified-worker"
main = "tests/worker.ts"
compatibility_date = "2024-09-09"

compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = 'testing'

[[kv_namespaces]]
binding = "KV"
id = "<ignored>"
preview_id = "<ignored>"
